CC=gcc

CFLAGS=-Wall -W -g -lm


all: proj1C differencer

proj1C: proj1C.c
	$(CC) proj1C.c $(CFLAGS) -o proj1C

differencer: differencer.c
	$(CC) differencer.c $(CFLAGS) -o differencer

clean:
	rm -f proj1C differencer *.o

